
class MockData {
  static final List<Map<String, dynamic>> bikes = [
    {
      'id': 'bike_1',
      'bike_name': 'Royal Enfield Classic 350',
      'brand': 'Royal Enfield',
      'model': 'Classic 350',
      'category': 'Cruiser',
      'rental_price': 1200.0,
      'security_deposit': 3000.0,
      'availability_status': 'Available',
      'registration_number': 'KA-01-HH-1234',
      'description': 'Iconic cruiser with timeless design and thumping exhaust note.',
      'color': 'Stealth Black',
      'engine_cc': 349,
      'fuel_type': 'Petrol',
      'transmission': 'Manual',
    },
    {
      'id': 'bike_2',
      'bike_name': 'Bajaj Pulsar NS200',
      'brand': 'Bajaj',
      'model': 'Pulsar NS200',
      'category': 'Sport',
      'rental_price': 800.0,
      'security_deposit': 2000.0,
      'availability_status': 'Available',
      'registration_number': 'MH-12-AB-9876',
      'description': 'Aggressive naked sport bike with liquid-cooled engine.',
      'color': 'Satin Pearl White',
      'engine_cc': 199,
      'fuel_type': 'Petrol',
      'transmission': 'Manual',
    },
    {
      'id': 'bike_3',
      'bike_name': 'Honda Activa 6G',
      'brand': 'Honda',
      'model': 'Activa 6G',
      'category': 'Scooter',
      'rental_price': 400.0,
      'security_deposit': 1000.0,
      'availability_status': 'Maintenance',
      'registration_number': 'DL-04-CD-5678',
      'description': 'India\'s best-selling automatic scooter. Perfect for city commutes.',
      'color': 'Pearl Precious White',
      'engine_cc': 109,
      'fuel_type': 'Petrol',
      'transmission': 'Automatic',
    },
    {
      'id': 'bike_4',
      'bike_name': 'KTM Duke 390',
      'brand': 'KTM',
      'model': 'Duke 390',
      'category': 'Sport',
      'rental_price': 1500.0,
      'security_deposit': 5000.0,
      'availability_status': 'Available',
      'registration_number': 'TN-09-XY-3456',
      'description': 'High-performance naked streetfighter with aggressive styling.',
      'color': 'Orange',
      'engine_cc': 373,
      'fuel_type': 'Petrol',
      'transmission': 'Manual',
    },
    {
      'id': 'bike_5',
      'bike_name': 'TVS Apache RTR 160',
      'brand': 'TVS',
      'model': 'Apache RTR 160 4V',
      'category': 'Street',
      'rental_price': 700.0,
      'security_deposit': 1500.0,
      'availability_status': 'On Rent',
      'registration_number': 'UP-16-YZ-7890',
      'description': 'Race-inspired street bike with advanced technology.',
      'color': 'Matte Blue',
      'engine_cc': 159,
      'fuel_type': 'Petrol',
      'transmission': 'Manual',
    },
    {
      'id': 'bike_6',
      'bike_name': 'Yamaha R15 V4',
      'brand': 'Yamaha',
      'model': 'YZF-R15 V4',
      'category': 'Sport',
      'rental_price': 1000.0,
      'security_deposit': 2500.0,
      'availability_status': 'Available',
      'registration_number': 'TS-07-EA-1122',
      'description': 'Supersport with delta-box frame and Variable Valve Actuation.',
      'color': 'Racing Blue',
      'engine_cc': 155,
      'fuel_type': 'Petrol',
      'transmission': 'Manual',
    },
    {
      'id': 'bike_7',
      'bike_name': 'Suzuki Access 125',
      'brand': 'Suzuki',
      'model': 'Access 125',
      'category': 'Scooter',
      'rental_price': 450.0,
      'security_deposit': 1000.0,
      'availability_status': 'Available',
      'registration_number': 'WB-02-PQ-3344',
      'description': 'Refined 125cc scooter ideal for comfortable daily rides.',
      'color': 'Pearl Mirage White',
      'engine_cc': 124,
      'fuel_type': 'Petrol',
      'transmission': 'Automatic',
    },
    {
      'id': 'bike_8',
      'bike_name': 'Hero Splendor Plus',
      'brand': 'Hero',
      'model': 'Splendor Plus',
      'category': 'Street',
      'rental_price': 300.0,
      'security_deposit': 500.0,
      'availability_status': 'On Rent',
      'registration_number': 'RJ-14-MN-5566',
      'description': 'India\'s most popular commuter bike. Fuel efficient and reliable.',
      'color': 'Black Silver',
      'engine_cc': 97,
      'fuel_type': 'Petrol',
      'transmission': 'Manual',
    },
    {
      'id': 'bike_9',
      'bike_name': 'Royal Enfield Himalayan',
      'brand': 'Royal Enfield',
      'model': 'Himalayan 411',
      'category': 'Cruiser',
      'rental_price': 1400.0,
      'security_deposit': 4000.0,
      'availability_status': 'Available',
      'registration_number': 'CH-01-AB-7788',
      'description': 'Purpose-built adventure tourer for highways and trails.',
      'color': 'Granite Black',
      'engine_cc': 411,
      'fuel_type': 'Petrol',
      'transmission': 'Manual',
    },
    {
      'id': 'bike_10',
      'bike_name': 'Ather 450X',
      'brand': 'Ather',
      'model': '450X Gen 3',
      'category': 'Scooter',
      'rental_price': 600.0,
      'security_deposit': 2000.0,
      'availability_status': 'Available',
      'registration_number': 'KA-03-TR-9900',
      'description': 'Premium electric scooter with smart connectivity.',
      'color': 'Space Grey',
      'engine_cc': 0,
      'fuel_type': 'Electric',
      'transmission': 'Automatic',
    },
    {
      'id': 'bike_11',
      'bike_name': 'Honda CB350 Hness',
      'brand': 'Honda',
      'model': 'CB350 H\'ness',
      'category': 'Cruiser',
      'rental_price': 1300.0,
      'security_deposit': 3500.0,
      'availability_status': 'Available',
      'registration_number': 'MH-14-LK-2233',
      'description': 'Elegant retro cruiser with Honda\'s refined engineering.',
      'color': 'Pearl Night Star Black',
      'engine_cc': 348,
      'fuel_type': 'Petrol',
      'transmission': 'Manual',
    },
    {
      'id': 'bike_12',
      'bike_name': 'Bajaj Dominar 400',
      'brand': 'Bajaj',
      'model': 'Dominar 400',
      'category': 'Sport',
      'rental_price': 1200.0,
      'security_deposit': 3000.0,
      'availability_status': 'Maintenance',
      'registration_number': 'GJ-05-HG-4455',
      'description': 'Power cruiser with touring capabilities and twin-barrel exhaust.',
      'color': 'Aurora Green',
      'engine_cc': 373,
      'fuel_type': 'Petrol',
      'transmission': 'Manual',
    },
    {
      'id': 'bike_13',
      'bike_name': 'Ola S1 Pro',
      'brand': 'Ola Electric',
      'model': 'S1 Pro',
      'category': 'Scooter',
      'rental_price': 550.0,
      'security_deposit': 1500.0,
      'availability_status': 'Available',
      'registration_number': 'KA-51-EF-6677',
      'description': 'Feature-rich electric scooter with premium build and MoveOS.',
      'color': 'Jet Black',
      'engine_cc': 0,
      'fuel_type': 'Electric',
      'transmission': 'Automatic',
    },
    {
      'id': 'bike_14',
      'bike_name': 'TVS NTORQ 125',
      'brand': 'TVS',
      'model': 'NTORQ 125',
      'category': 'Scooter',
      'rental_price': 450.0,
      'security_deposit': 1000.0,
      'availability_status': 'Available',
      'registration_number': 'KL-07-ZX-8899',
      'description': 'Sporty 125cc scooter with SmartXconnect Bluetooth tech.',
      'color': 'Metallic Red',
      'engine_cc': 124,
      'fuel_type': 'Petrol',
      'transmission': 'Automatic',
    },
    {
      'id': 'bike_15',
      'bike_name': 'KTM RC 200',
      'brand': 'KTM',
      'model': 'RC 200',
      'category': 'Sport',
      'rental_price': 1100.0,
      'security_deposit': 2500.0,
      'availability_status': 'On Rent',
      'registration_number': 'AP-09-CV-1122',
      'description': 'Faired sport bike with sharp handling and lightweight chassis.',
      'color': 'Dark Silver Metallic',
      'engine_cc': 199,
      'fuel_type': 'Petrol',
      'transmission': 'Manual',
    },
    {
      'id': 'bike_16',
      'bike_name': 'Hero Xpulse 200',
      'brand': 'Hero',
      'model': 'Xpulse 200 4V',
      'category': 'Street',
      'rental_price': 800.0,
      'security_deposit': 2000.0,
      'availability_status': 'Available',
      'registration_number': 'HR-26-BN-3344',
      'description': 'Off-road capable adventure bike with rally-tuned suspension.',
      'color': 'Trail Green',
      'engine_cc': 199,
      'fuel_type': 'Petrol',
      'transmission': 'Manual',
    },
    {
      'id': 'bike_17',
      'bike_name': 'Yamaha MT-15',
      'brand': 'Yamaha',
      'model': 'MT-15 V2',
      'category': 'Street',
      'rental_price': 900.0,
      'security_deposit': 2000.0,
      'availability_status': 'Available',
      'registration_number': 'PB-08-AS-5566',
      'description': 'Dark warrior naked streetfighter with VVA technology.',
      'color': 'Dark Matt Blue',
      'engine_cc': 155,
      'fuel_type': 'Petrol',
      'transmission': 'Manual',
    },
    {
      'id': 'bike_18',
      'bike_name': 'Suzuki Gixxer SF',
      'brand': 'Suzuki',
      'model': 'Gixxer SF 250',
      'category': 'Sport',
      'rental_price': 850.0,
      'security_deposit': 2000.0,
      'availability_status': 'Available',
      'registration_number': 'OD-02-QW-7788',
      'description': 'Full-faired sport tourer with oil-cooled SOHC engine.',
      'color': 'Metallic Triton Blue',
      'engine_cc': 249,
      'fuel_type': 'Petrol',
      'transmission': 'Manual',
    },
    {
      'id': 'bike_19',
      'bike_name': 'Royal Enfield Meteor 350',
      'brand': 'Royal Enfield',
      'model': 'Meteor 350',
      'category': 'Cruiser',
      'rental_price': 1350.0,
      'security_deposit': 3500.0,
      'availability_status': 'Available',
      'registration_number': 'UP-32-DF-9900',
      'description': 'Easy-going cruiser with Tripper navigation and refined engine.',
      'color': 'Fireball Yellow',
      'engine_cc': 349,
      'fuel_type': 'Petrol',
      'transmission': 'Manual',
    },
    {
      'id': 'bike_20',
      'bike_name': 'Honda Dio',
      'brand': 'Honda',
      'model': 'Dio 125',
      'category': 'Scooter',
      'rental_price': 350.0,
      'security_deposit': 800.0,
      'availability_status': 'Available',
      'registration_number': 'TN-22-KJ-1234',
      'description': 'Sporty urban scooter with eSP+ engine and silent start.',
      'color': 'Matte Axis Grey Metallic',
      'engine_cc': 124,
      'fuel_type': 'Petrol',
      'transmission': 'Automatic',
    }
  ];

  static void initializeImages() {
    // Map each bike to a unique image based on its ID
    final imageMap = {
      'bike_1': 'assets/images/bikes/royal_enfield_classic_1784625681147.png',
      'bike_2': 'assets/images/bikes/bajaj_pulsar_ns200_1784625530397.png',
      'bike_3': 'assets/images/bikes/scooter.png',
      'bike_4': 'assets/images/bikes/ktm_rc_390_1784625498409.png',
      'bike_5': 'assets/images/bikes/tvs_apache_310_1784625571067.png',
      'bike_6': 'assets/images/bikes/yamaha_r15_v4_1784625508793.png',
      'bike_7': 'assets/images/bikes/scooter.png',
      'bike_8': 'assets/images/bikes/adventure_bike.png',
      'bike_9': 'assets/images/bikes/cruiser_bike.png',
      'bike_10': 'assets/images/bikes/scooter.png',
      'bike_11': 'assets/images/bikes/royal_enfield_meteor_1784625484165.png',
      'bike_12': 'assets/images/bikes/bajaj_dominar_400_1784625560737.png',
      'bike_13': 'assets/images/bikes/scooter.png',
      'bike_14': 'assets/images/bikes/scooter.png',
      'bike_15': 'assets/images/bikes/ktm_rc_390_1784625498409.png',
      'bike_16': 'assets/images/bikes/adventure_bike.png',
      'bike_17': 'assets/images/bikes/yamaha_mt_15_1784625520148.png',
      'bike_18': 'assets/images/bikes/sport_bike.png',
      'bike_19': 'assets/images/bikes/royal_enfield_meteor_1784625484165.png',
      'bike_20': 'assets/images/bikes/scooter.png',
    };

    for (var bike in bikes) {
      final id = bike['id'] as String;
      if (imageMap.containsKey(id)) {
        bike['image_url'] = imageMap[id];
      } else {
        // Fallback by category
        switch (bike['category']) {
          case 'Cruiser':
            bike['image_url'] = 'assets/images/bikes/cruiser_bike.png';
            break;
          case 'Sport':
            bike['image_url'] = 'assets/images/bikes/sport_bike.png';
            break;
          case 'Scooter':
            bike['image_url'] = 'assets/images/bikes/scooter.png';
            break;
          case 'Street':
          default:
            bike['image_url'] = 'assets/images/bikes/adventure_bike.png';
            break;
        }
      }
    }
  }

  static final List<Map<String, dynamic>> customers = List.generate(60, (index) {
    final firstNames = ['Amit', 'Rahul', 'Priya', 'Sneha', 'Vikram', 'Neha', 'Rohan', 'Aditi', 'Karan', 'Pooja', 'Suresh', 'Deepa'];
    final lastNames = ['Sharma', 'Verma', 'Patel', 'Singh', 'Kumar', 'Gupta', 'Iyer', 'Reddy', 'Das', 'Joshi'];
    final statuses = ['APPROVED', 'APPROVED', 'APPROVED', 'PENDING', 'REJECTED'];
    final firstName = firstNames[index % firstNames.length];
    final lastName = lastNames[(index + 3) % lastNames.length];
    
    return {
      'id': 'cust_$index',
      'name': '$firstName $lastName',
      'phone': '+91 9${(876543210 + index * 1234).toString().padLeft(9, '0')}',
      'email': '${firstName.toLowerCase()}.${lastName.toLowerCase()}$index@gmail.com',
      'kycStatus': statuses[index % statuses.length],
      'dlUrl': 'https://placeholder.com/dl_$index.jpg',
      'aadhaarUrl': 'https://placeholder.com/aadhaar_$index.jpg',
      'isBlocked': index % 15 == 0,
    };
  });

  static final List<Map<String, dynamic>> bookings = List.generate(100, (index) {
    final statuses = ['COMPLETED', 'PENDING', 'ACTIVE', 'CONFIRMED', 'CANCELLED', 'PENDING'];
    final bike = bikes[index % bikes.length];
    final customer = customers[index % customers.length];
    final days = (index % 5) + 1;
    final price = bike['rental_price'] as double;
    
    return {
      'id': 'bk_$index',
      'booking_number': 'BRN${10000 + index}',
      'customer_name': customer['name'],
      'bike_name': bike['bike_name'],
      'bike_id': bike['id'],
      'pickup_date': DateTime.now().subtract(Duration(days: index)).toIso8601String(),
      'return_date': DateTime.now().subtract(Duration(days: index - days)).toIso8601String(),
      'duration_days': days,
      'price': price,
      'deposit': bike['security_deposit'],
      'taxes': price * days * 0.18,
      'final_amount': (price * days) + (price * days * 0.18),
      'booking_status': statuses[index % statuses.length],
      'payment_status': 'PAID'
    };
  });

  static final Map<String, dynamic> dashboardStats = {
    'total_bikes': 20,
    'available_bikes': 15,
    'active_rentals': 3,
    'pending_bookings': 2,
    'today_revenue': 4500.0,
    'monthly_revenue': 125000.0,
  };
}
