name: unified_app
description: Customer App for Bike Rental Platform
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  shared:
    path: ../../shared
  go_router: ^12.1.1
  flutter_riverpod: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
